### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by airs0urce** [alemures/gcm-xmpp#1]
I was getting ECONNRESET for a long time and didn't know from which module.
Then I added "longjohn" (http://npmjs.com/longjohn) in project and got this:

Error: read ECONNRESET at exports._errnoException (util.js:1007:11)
     at TLSWrap.onread (net.js:563:26)
     ---------------------------------------------
     at Client._addListeners (/home/<path>/node_modules/gcm-xmpp/lib/Client.js:155:19)
     at Client.connect (/home/<path>/node_modules/gcm-xmpp/lib/Client.js:128:8)
     at new PushHelper (/home/<path>/modules/PushHelper.js:86:17)
     at Function.PushHelper.instance (/home/<path>/modules/PushHelper.js:95:21)
     at new module.exports (/home/<path>/modules/API.js:84:31)
     at Function.API.instance (/home/<path>/modules/API.js:123:21)
     at /home/<path>/modules/nodeRPC.js:37:19

I suppose, gcm-xmpp doesn't handle "error" event somewhere.
At least I had same issue with websocket implementation and solved by this:

```
socket.on('error', function(event) {
            if ('ECONNRESET' != event.code) {
                // log error
            }
});
```

Also not sure will gcm-xmpp send push notification again if this error happened.
If not - I think it should, else notification will be lost.

**Comment by alemures** [comment]
The client instance is already emitting the event 'error' whenever an error happens so, you just need to listen to that event on your client instance. Because that is a special event, if a client emits an event 'error' and nobody is listening to that event, the node.js process will be stopped showing the emitted value.
